### ISSUE TITLE
The package 'react-native-folding-feature' doesn't seem to be linked

### ISSUE THREAD

**Issue by joycelsq84** [joel611/react-native-folding-feature#1]
hi

i get error 
 Error: The package 'react-native-folding-feature' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo Go
, js engine: hermes

what should i do?

Thanks.

**Comment by joel611** [comment]
@joycelsq84

It should autolinking by default.
https://github.com/react-native-community/cli/blob/main/docs/autolinking.md

you can try run build command again
